spring:
  application:
    name: cardgame
  datasource:
    url: jdbc:h2:mem:cardgame-db
    driver-class-name: org.h2.Driver
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
  cache:
    type:

logging:
  level:
    root: INFO
  file:
    name: logs/app.log

omdb:
  api-key:
